#!/bin/sh



if [ $# -ne 1 ]; then

	echo "You must supply one parameter {start|stop|restart}"

	exit 1
fi

#Redes

DMZ_NET="172.20.108.0/24"

LAN_NET="192.168.108.0/24"

#Interfaces

DMZ_IF="DMZ"

WAN_IF="eth0"

LAN_IF="LAN"

#IPs

DMZ_IP="172.20.108.254"

WAN_IP="10.3.4.166"

LAN_IP="192.168.108.254"



case $1 in

"start")

	$0 stop

	echo "1" > /proc/sys/net/ipv4/ip_forward

	iptables -P INPUT DROP

	iptables -P OUTPUT DROP

	iptables -P FORWARD DROP

	iptables -A INPUT -i $WAN_IF -d $WAN_IP -p tcp --dport 2222 -j ACCEPT

	iptables -A INPUT -i $LAN_IF -s $LAN_NET -d $LAN_IP -p tcp --dport 2222 -j ACCEPT

	iptables -A INPUT -i $DMZ_IF -s $DMZ_NET -d $DMZ_IP  -p tcp --dport 2222 -j ACCEPT

	iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

	iptables -A OUTPUT -o $WAN_IF -p udp --dport 67 --sport 68 -j ACCEPT

	iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT



	# cliente PING (icmp)

	iptables -A OUTPUT -p icmp -j ACCEPT


	iptables -A OUTPUT -p udp --dport 53 -j ACCEPT


	iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT


	iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
	iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
	iptables -A FORWARD -i $DMZ_IF -s $DMZ_NET -o $WAN_IF -p udp --dport 53 -j ACCEPT
	iptables -t nat -A POSTROUTING -s $DMZ_NET -o $WAN_IF -p udp --dport 53 -j SNAT --to $WAN_IP
	iptables -A FORWARD -i $DMZ_IF -s $DMZ_NET -o $WAN_IF -p tcp --dport 80 -j ACCEPT
	iptables -t nat -A POSTROUTING -s $DMZ_NET -o $WAN_IF -p tcp --dport 80 -j SNAT --to $WAN_IP
	iptables -A FORWARD -i $DMZ_IF -s $DMZ_NET -o $WAN_IF -p tcp --dport 443 -j ACCEPT
	iptables -t nat -A POSTROUTING -s $DMZ_NET -o $WAN_IF -p tcp --dport 443 -j SNAT --to $WAN_IP
	iptables -A FORWARD -i $LAN_IF -s $LAN_NET -o $DMZ_IF -d $DMZ_NET -p tcp --dport 22 -j ACCEPT
	iptables -A FORWARD -i $LAN_IF -s $LAN_NET -o $DMZ_IF -d $DMZ_NET -p udp --dport 53 -j ACCEPT
	iptables -A FORWARD -i $LAN_IF -s $LAN_NET -o $DMZ_IF -d $DMZ_NET -p tcp --dport 80 -j ACCEPT
	iptables -A FORWARD -i $LAN_IF -s $LAN_NET -o $DMZ_IF -d $DMZ_NET -p tcp --dport 443 -j ACCEPT
	iptables -A FORWARD -i $LAN_IF -s $LAN_NET -o $WAN_IF -p tcp --dport 80 -j ACCEPT
	iptables -t nat -A POSTROUTING -s $LAN_NET -o $WAN_IF -p tcp --dport 80 -j SNAT --to $WAN_IP
	iptables -A FORWARD -i $LAN_IF -s $LAN_NET -o $WAN_IF -p tcp --dport 443 -j ACCEPT
	iptables -t nat -A POSTROUTING -s $LAN_NET -o $WAN_IF -p tcp --dport 443 -j SNAT --to $WAN_IP
	iptables -A FORWARD -p icmp -j ACCEPT
	iptables -t nat -A POSTROUTING -o $WAN_IF -p icmp  -j SNAT --to $WAN_IP
	iptables -A FORWARD -i $WAN_IF -o $DMZ_IF -p tcp --dport 80 -d 172.20.108.100 -j ACCEPT
	iptables -t nat -A PREROUTING -i $WAN_IF -p tcp --dport 22 -j DNAT --to 172.20.108.100
	iptables -A FORWARD -i $WAN_IF -o $DMZ_IF -p tcp --dport 22 -d 172.20.108.100 -j ACCEPT
 	iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

        iptables -t nat -A PREROUTING -i $WAN_IF -p udp --dport 53 -j DNAT --to 172.20.108.100
        iptables -A FORWARD -i $WAN_IF -o $DMZ_IF -p udp --dport 53 -d 172.20.108.100 -j ACCEPT
	iptables -t nat -A PREROUTING -i $WAN_IF -p tcp --dport 53 -j DNAT --to 172.20.108.100
        iptables -A FORWARD -i $WAN_IF -o $DMZ_IF -p tcp --dport 53 -d 172.20.108.100 -j ACCEPT
	;;


"stop")


	iptables -F
	iptables -t nat -F
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT
	iptables -P FORWARD ACCEPT

	echo "0" > /proc/sys/net/ipv4/ip_forward

	;;

"restart")

	$0 stop

	$0 start

	;;

*)

	echo "Se necesita un parametro valido [start | stop]"

	exit 1

	;;

esac

exit 0
